const ADDALL = 'ADDALL'
const CHECK = 'CHECK'
const ADDONE = 'ADDONE'
const UPDATETODO = 'UPDATETODO'
const DELETE = 'DELETE'
const SET_USER= "SET_USER"
const LOG_OUT ="LOG_OUT"

export  {ADDALL, CHECK, ADDONE, UPDATETODO, DELETE, SET_USER, LOG_OUT }
